hosts:
  - localhost:8080
  - localhost:8081
  - localhost:8082

tests:
  - name: "Small Upload Test"
    operation: upload
    repeat: 3
    size: 16KB

  - name: "Medium Download Test"
    operation: download
    repeat: 3
    size: 256KB

  - name: "Large Upload Test"
    operation: upload
    repeat: 2
    size: 1MB

  - name: "Large Download Test"
    operation: download
    repeat: 2
    size: 1MB

  - name: "Max Size Test"
    operation: download
    repeat: 1
    size: 16MB
